# name: Intializing Database

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  init-db:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: annusingh1211/banking-app-2-tier
          ref: main

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::540034108652:role/github-action-deploy-role-cicd-new
          aws-region: eu-north-1

      - name: Upload files to S3
        run: |
          aws s3 mb s3://540034108652-devops-scripts --region eu-north-1 2>/dev/null || true

          aws s3 cp init.py s3://540034108652-devops-scripts/init.py --region eu-north-1
          aws s3 cp init.sql s3://540034108652-devops-scripts/init.sql --region eu-north-1

          echo "✅ Files uploaded successfully"

      - name: Initialize Database on EC2
        id: init
        run: |
          CMD_ID=$(aws ssm send-command \
            --targets "Key=tag:App,Values=flask" \
            --document-name "AWS-RunShellScript" \
            --parameters '{
              "commands":[
                "aws s3 cp s3://540034108652-devops-scripts/init.py /tmp/init.py",
                "aws s3 cp s3://540034108652-devops-scripts/init.sql /tmp/init.sql",
                "python3 /tmp/init.py",
                "rm -f /tmp/init.py /tmp/init.sql"
              ]
            }' \
            --query "Command.CommandId" \
            --output text \
            --region eu-north-1)

          echo "cmd_id=$CMD_ID" >> $GITHUB_OUTPUT

      - name: Wait for SSM execution
        run: sleep 30

      - name: Show Results
        run: |
          aws ssm list-command-invocations \
            --command-id "${{ steps.init.outputs.cmd_id }}" \
            --details \
            --region eu-north-1 \
            --output text

          FAILED=$(aws ssm list-command-invocations \
            --command-id "${{ steps.init.outputs.cmd_id }}" \
            --query "length(CommandInvocations[?Status!='Success'])" \
            --output text \
            --region eu-north-1)

          if [ "$FAILED" -gt 0 ]; then
            echo "::error::Database initialization failed on $FAILED instance(s)"
            exit 1
          fi

          echo "✅ Database initialized successfully on all EC2 instances."